Repository Reelstack/reelstack, pull requests merged in 2025-09, with the labels that each got.

#15 Implementação da Arquitetura Modular da API OMDb e Hooks React
  .env.local.example
  .gitignore
  DOCUMENTACAO_API.md
  src/hooks/index.ts
  src/hooks/useOMDB.ts
  src/pages/Home/index.tsx
  src/pages/Home/style.module.css
  src/services/api/base.ts
  src/services/api/omdb.ts
  src/services/api/types.ts
  src/services/index.ts
  src/styles/global.css
Labels: documentation, enhancement, Sprint 1

#20 criação de background dinamico e adição de botões para debug
  public/goncha.jpg
  src/components/BackgroundBody/index.tsx
  src/components/RouterLink/index.tsx
  src/pages/Home/index.tsx
  src/pages/Login/index.tsx
  src/pages/Profile/index.tsx
  src/styles/global.css
Labels: documentation, enhancement, Sprint 1

#29 Homescreen v0.2
  package-lock.json
  package.json
  src/assets/arrow-increase.svg
  src/assets/arrow-right-circle-filled.svg
  src/assets/arrow-right-circle.svg
  src/assets/filter.svg
  src/assets/react.svg
  src/pages/Home/index.tsx
  src/pages/Home/style.module.css
  src/styles/global.css
Labels: enhancement, Sprint 1

#34 Homescreen v0.2
  src/assets/arrow-decrease.svg
  src/assets/arrow-increase.svg
  src/pages/Home/index.tsx
  src/pages/Home/style.module.css
Labels: bug, enhancement, Sprint 1

#36 Adicionar guia de execução do projeto (DOCUMENTACAO_EXECUCAO.md)
  DOCUMENTACAO_EXECUCAO.md
Labels: documentation, Sprint 1

#37 Atualizar DOCUMENTACAO_EXECUCAO.md com links clicáveis para arquivos e pastas
  DOCUMENTACAO_EXECUCAO.md
Labels: documentation, enhancement, Sprint 1

#41 Merge branch 'developer' into 'main' — Nova documentação, animações e melhorias visuais
  DOCUMENTACAO_EXECUCAO.md
  package-lock.json
  package.json
  src/assets/arrow-decrease.svg
  src/assets/arrow-increase.svg
  src/assets/arrow-right-circle-filled.svg
  src/assets/arrow-right-circle.svg
  src/assets/filter.svg
  src/assets/react.svg
  src/pages/Home/index.tsx
  src/pages/Home/style.module.css
  src/styles/global.css
Labels: bug, documentation, enhancement, help wanted, Sprint 1

#54 Gabs
  REQUISITO_SOFTWARE.md
Labels: documentation

#55 Developer
  REQUISITO_SOFTWARE.md
  src/pages/Login/index.tsx
Labels: documentation

#57 Login v1
  package-lock.json
  package.json
  src/components/LoginForm/index.tsx
  src/components/LoginForm/styles.module.css
  src/components/SignUpForm/index.tsx
  src/components/SignUpForm/styles.module.css
  src/contexts/UserContext/userContext.tsx
  src/contexts/UserContext/userHook.tsx
  src/contexts/UserContext/userReducer.ts
  src/contexts/UserContext/userTypes.ts
  src/global.d.ts
  src/lib/database.types.ts
  src/pages/Login/index.tsx
  src/pages/Login/style.module.css
Labels: enhancement, Sprint 2

#60 Requisito de software
  REQUISITO_SOFTWARE.md
Labels: documentation, Sprint 3

#61 Update user requirements in REQUISITO_SOFTWARE.md
  REQUISITO_SOFTWARE.md
Labels: documentation, Sprint 3

#77 PR: Atualização do Documento de Requisitos do ReelStack v2
  REQUISITO_SOFTWARE.md
  public/Diagrama simplificado.png
  public/Package Coleções.png
  public/Package Gerenciamento de Usuário.png
  public/Package Interação com filmes.png
Labels: documentation, Sprint 3

#82 Pull Request: Atualização no Documento de Requisitos & Autenticação / Contexto de Usuário
  REQUISITO_SOFTWARE.md
  public/Diagrama simplificado.png
  public/Package Coleções.png
  public/Package Gerenciamento de Usuário.png
  public/Package Interação com filmes.png
  src/App.tsx
  src/TestAuth.tsx
  src/TestSession.tsx
  src/components/LoginForm/index.tsx
  src/components/SignUpForm/index.tsx
  src/components/SignUpForm/styles.module.css
  src/contexts/AuthContext/authContext.tsx
  src/contexts/UserContext/userContext.tsx
  src/global.d.ts
  src/lib/database.types.ts
  src/lib/supabaseClient.ts
  src/main.tsx
  src/pages/Home/index.tsx
  src/pages/Login/index.tsx
  src/pages/Login/style.module.css
  src/routers/GuardedRoute/index.tsx
  src/routers/MainRouter/index.tsx
  src/styles/theme.css
Labels: documentation, enhancement, Sprint 3
